### ISSUE TITLE
Breaking block gives item back without NBT

### ISSUE THREAD

**Issue by Lvgraef** [Itskillerluc/Alchemical_Brewery#3]
### Operating System

Windows

### Minecraft Version

1.18.2

### Forge Version

all

### Alchemical Brewery Version

hotfix 

### Singleplayer or Multiplayer

sp

### Description

Breaking block gives elements wihtout nbt back

### Steps to Reproduce

put element with nbt in destroy block

### Suspected Cause

The cause is the nbt being stored in a different spot than the itemstack takes it from

The solution is to read those tags from that spot and to store it in the correct spot

**Comment by BeansBeefBroccoli** [comment]
How did you fix this?

**Comment by Lvgraef** [comment]
Currently it only works  with specific items but I will make it work with every item. it manuelly transfers the nbt from the ForgeCaps to the tags, idk why it puts it in Forgecaps tho.

**Comment by BeansBeefBroccoli** [comment]
Huh, ok.
